# Generated by Django 5.0.6 on 2024-07-05 02:43

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, default='servicios\\default-service.jpeg', null=True, upload_to=usuarios.models.get_image_filename),
        ),
    ]
