# Generated by Django 4.2.13 on 2024-06-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte')], max_length=2, verbose_name='Tipo de Documento')),
                ('documento', models.PositiveIntegerField(unique=True, verbose_name='Documento')),
            ],
        ),
    ]
